wandb_version: 1

epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
model_order:
  desc: null
  value: 3
model_steps:
  desc: null
  value: 3
model_rank:
  desc: null
  value: 8
kernel:
  desc: null
  value: 3
total_frames:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700953847.050056
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.6
      5: 0.16.0
      8:
      - 5
      13: darwin-arm64
